defmodule PoeProfit.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:currencies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :poe_id, :text
      add :name, :text
      add :icon_url, :text
      add :league, :text
      add :price_in_exalted, :float
      add :last_price_update, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:currencies, [:poe_id, :league], name: "currencies_poe_id_index")
  end

  def down do
    drop_if_exists unique_index(:currencies, [:poe_id, :league], name: "currencies_poe_id_index")

    drop table(:currencies)
  end
end
