defmodule PoeProfit.Repo.Migrations.AddItemStats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stats, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :poe_id, :text, null: false
      add :text, :text, null: false
      add :type_id, :uuid, null: false
    end

    create table(:stat_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:stats) do
      modify :type_id,
             references(:stat_types,
               column: :id,
               name: "stats_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:stats, [:poe_id, :text], name: "stats_poe_id_index")

    alter table(:stat_types) do
      add :name, :text, null: false
    end

    create unique_index(:stat_types, [:name], name: "stat_types_name_index")
  end

  def down do
    drop_if_exists unique_index(:stat_types, [:name], name: "stat_types_name_index")

    alter table(:stat_types) do
      remove :name
    end

    drop_if_exists unique_index(:stats, [:poe_id, :text], name: "stats_poe_id_index")

    drop constraint(:stats, "stats_type_id_fkey")

    alter table(:stats) do
      modify :type_id, :uuid
    end

    drop table(:stat_types)

    drop table(:stats)
  end
end
